// Supplied destinations and user-requested northern coverage cities.
// Coordinates are schematic city markers, not branch addresses.
export const coverageCities = [
  {
    name: 'Ahmednagar / Supa',
    region: 'west',
    lat: 19.04,
    lon: 74.4,
    label: true,
  },
  { name: 'Mahad', region: 'west', lat: 18.08, lon: 73.42, label: true },
  { name: 'Lote', region: 'west', lat: 17.57, lon: 73.48, label: true },
  { name: 'Hyderabad', region: 'south', lat: 17.39, lon: 78.49, label: true },
  {
    name: 'Visakhapatnam (Vizag)',
    region: 'south',
    lat: 17.69,
    lon: 83.22,
    label: true,
  },
  { name: 'Nellore', region: 'south', lat: 14.44, lon: 79.99, label: true },
  { name: 'Chennai', region: 'south', lat: 13.08, lon: 80.27, label: true },
  { name: 'Cuddalore', region: 'south', lat: 11.75, lon: 79.77, label: true },
  { name: 'Erode', region: 'south', lat: 11.34, lon: 77.72, label: true },
  {
    name: 'Kochi (Cochin)',
    region: 'south',
    lat: 9.93,
    lon: 76.27,
    label: true,
  },
  {
    name: 'Bengaluru (Bangalore)',
    region: 'south',
    lat: 12.97,
    lon: 77.59,
    label: true,
  },
  { name: 'Nagpur', region: 'central', lat: 21.15, lon: 79.09, label: true },
  { name: 'Kolkata', region: 'east', lat: 22.57, lon: 88.36, label: true },
  { name: 'Delhi', region: 'north', lat: 28.61, lon: 77.21, label: true },
  { name: 'Jaipur', region: 'north', lat: 26.91, lon: 75.79, label: true },
  { name: 'Chandigarh', region: 'north', lat: 30.73, lon: 76.78, label: true },
  { name: 'Ludhiana', region: 'north', lat: 30.9, lon: 75.86, label: true },
  { name: 'Amritsar', region: 'north', lat: 31.63, lon: 74.87, label: true },
  { name: 'Jammu', region: 'north', lat: 32.73, lon: 74.86, label: true },
  { name: 'Dehradun', region: 'north', lat: 30.32, lon: 78.03, label: true },
  { name: 'Lucknow', region: 'north', lat: 26.85, lon: 80.95, label: true },
  { name: 'Kanpur', region: 'north', lat: 26.45, lon: 80.33, label: true },
  { name: 'Agra', region: 'north', lat: 27.18, lon: 78.01, label: true },
] as const;
